### ISSUE TITLE
USER STORY: As a player, I want to have the option to play in a 1-player mode where I can control Luke Skywalker and face off against a wave of challenging enemies, such as stormtroopers, in locations like Yoda's swamp.

### ISSUE THREAD

**Issue by bezebee** [bezebee/star-wars-hackathon#9]
***Epic***: Single-player Mode

***User Story***
As a player, I want to have the option to play in a 1-player mode where I can control Luke Skywalker and face off against a wave of challenging enemies, such as stormtroopers, in locations like Yoda's swamp.

***Acceptance Criteria***

- [ ] As a player, I can select the 1-player mode from the main menu.
- [ ] As a player, I control Luke Skywalker and face off against waves of challenging enemies, such as stormtroopers.
- [ ] As a player, I can fight in various locations, including Yoda's swamp.
- [ ] As a player, the game progresses through multiple levels, each with increasing difficulty.
- [ ] As a player, the game ends when either I defeat all enemies or my character's health reaches zero.

***Tasks***
